### ISSUE TITLE
Fixing dungeon crawl structure - 421

### ISSUE THREAD

**Issue by OmIAm** [m1jordanallen/1.19OceanSurvival#107]
![image](https://github.com/m1jordanallen/1.19OceanSurvival/assets/141457221/cd3efb0a-1ef1-4239-867b-c98471c9ba97)

Clips by 421 for comparison on the same seed:

Clips for this ^.
Before: https://clips.twitch.tv/NiceAuspiciousNewtSeemsGood-dFsxV8D3HGW4DF7X

After: https://clips.twitch.tv/RealBlitheCasettePartyTime-eKy3PBqpU3RV29OU

**Comment by m1jordanallen** [comment]
done in 0.0.9
