### ISSUE TITLE
Fire from warrior rage

### ISSUE THREAD

**Issue by OmIAm** [m1jordanallen/1.19OceanSurvival#113]
Jon has complained several times about Warrior Rage thing doing fire damage to mobs and, with endermen, making the buffed ones really hard to kill.

If this is something you want to stop, fire damage can be turned off on the last line of the "warriorrage-common.toml" config file.

**Comment by OmIAm** [comment]
Jon isn't sure if he wants this removed or not.   Leaving it here incase he decides.

**Comment by m1jordanallen** [comment]
pretty sure we are removing warriors rage, but Im keeping this open in case we keep it for the config location. Thank you!

**Comment by m1jordanallen** [comment]
removed in 0.0.9
