### ISSUE TITLE
Mimics and Mob Grinding Utils

### ISSUE THREAD

**Issue by OmIAm** [m1jordanallen/1.19OceanSurvival#115]
Mimic spawners are a thing and you can get all the artifact loot quickly.

To stop it from being swabbed add "artifacts:mimic" to this config:

\mob_grinding_utils-1.19.2-0.4.49\data\mob_grinding_utils\tags\entity_types\no_swab.json

----------

To stop spawn eggs from being used in a spawner, add "artifacts:mimic" to config\apotheosis\spawner.cfg

----------

I'm pretty sure there's a way to exclude mobs from the enchant dropping spawn eggs but I can't seem to find it.

**Comment by OmIAm** [comment]
Or just remove artifacts:mimic_spawn_egg entirely.  *Shrug*

**Comment by 4tw0ne** [comment]
A nerf will be implemented to prevent the mimics from being used in spawners.

Using the 'config\apotheosis\spawner.cfg' suggestion. 

The rest I believe is not needed, as it would be tedious to get enough spawn eggs to matter.
Unless someone wants to use Soul shards :)
