### ISSUE TITLE
Island gen

### ISSUE THREAD

**Issue by OmIAm** [m1jordanallen/1.19OceanSurvival#124]
Ok, here's the best I can do to suit what Jon is wanting.  One thing that needs to be made clear:  Biome generation is still like vanilla.  You get big swaths of related biomes.  If you spawn in mountains there's probably more of them around.  The terrain gen is as close as I can come to vanilla.  Lots of flat islands for base, still some hills/swamps/etc.  Most of the "normal" terrain gen stops about 150 or so because of the size of the islands.  Several biomes still go into the 200's. (edited)

```
{
  "islandSize": 90.0,
  "islandSeperation": 270,
  "domainWarpNoise": {
    "octaves": 1,
    "horizontalFrequency": 8.0,
    "verticalFrequency": 8.0,
    "amplitude": 1,
    "lacunarity": 2,
    "persistence": 1
  },
  "hardcoreMode": false
}
```

**Comment by OmIAm** [comment]
This has been tested in 0.0.9hotfix1

**Comment by OmIAm** [comment]
That has been updated to size 90, separation 270 and is working properly.

I had size 100, separation 250 and it stopped dungeon gen when I turned BYG back on.

**Comment by m1jordanallen** [comment]
Ced fixed the underlying issue with an Island Dongle
