### ISSUE TITLE
Twilight Forest final boss not in quest book

### ISSUE THREAD

**Issue by Hamparty** [m1jordanallen/1.19OceanSurvival#128]
Elder Lich. Bams requests it gets knockback resistance.

**Comment by 4tw0ne** [comment]
Boss Quest added to 'Way of the Warrior' in "4tw0ne_QuestBook_Edits_0.3".

Notes for applying Knockback....
This boss is from 'twilighttweaks-1.19.2-1.2'.
Unpacking that Jar, the boss is generated by an MCfunction file located here "twilighttweaks-1.19.2-1.2\data\twilighttweaks\functions\final_boss_example.mcfunction"

I recommend the effect be applied to the books as well
