### ISSUE TITLE
MiniChad crash

### ISSUE THREAD

**Issue by 4tw0ne** [m1jordanallen/1.19OceanSurvival#130]
Using version "mp5 0.0.9hotfix1" 
minichad-1.19.2-0.8.3-RC

While Minichads are in the overworld, and holding Dirt; go into another dimension.
Sometimes after a few moments the following crash happens; on a few occasions. 

[latest.log](https://github.com/m1jordanallen/1.19OceanSurvival/files/15370158/latest.log)
[debug.log](https://github.com/m1jordanallen/1.19OceanSurvival/files/15370159/debug.log)
[crash-2024-05-18_14.01.32-server.txt](https://github.com/m1jordanallen/1.19OceanSurvival/files/15370160/crash-2024-05-18_14.01.32-server.txt)

**Comment by CedKilleur** [comment]
Fixed in MiniChad 0.8.4 ;)
