### ISSUE TITLE
Create Minecart Contraptions break save-games

### ISSUE THREAD

**Issue by MrSelenix** [m1jordanallen/1.19OceanSurvival#20]
mp5 v0.0.3 via curseforge
win11
java v8 update 361 (build 1.8.0_361-b09)
8192MB RAM allocation

Having any Create minecart contraption exist in the world causes "invalid player data" or "disconnected" when trying to join single player worlds. 
Log file: [2023-07-26-5.log.gz](https://github.com/m1jordanallen/1.19OceanSurvival/files/12172285/2023-07-26-5.log.gz)

**Comment by MrSelenix** [comment]
Temp Fixes involve deleting files located in ../Madpack51/saves/'worldname'/entities/ 

This deletes all entities, including the offending minecart. 
Assuming the player is reasonably close to world-spawn. deleting just r.0.#.mca files should be enough

**Comment by m1jordanallen** [comment]
I updated create and tweaked forge versions. Maybe try again in 0.0.4 and let us know how it goes.

**Comment by MrSelenix** [comment]
Can confirm at this point in time, minecart contraptions do not seem to break save games anymore (yet)
