### ISSUE TITLE
Crash during Launch

### ISSUE THREAD

**Issue by 4tw0ne** [m1jordanallen/1.19OceanSurvival#25]
Using 0.0.3 multiMC, Windows 10, 10GB ram allocated

This was during launch of the pack.

From what I can understand of the log, it is fishingvalley related 

[crash-2023-07-29_14.32.16-fml.txt](https://github.com/m1jordanallen/1.19OceanSurvival/files/12209952/crash-2023-07-29_14.32.16-fml.txt)

**Comment by CedKilleur** [comment]
FIXED in Fishing Valley 0.8+ ;)
