### ISSUE TITLE
Conflicting Smelting stuff

### ISSUE THREAD

**Issue by KinamKrindar** [m1jordanallen/1.19OceanSurvival#26]
"Oh the biomes you'll go" has multiple color sands (found some naturally spawning, black, blue, pink, purple). Checking "U"ses in JEI shows it can be used as regular sand for all recipes that require sand. HOWEVER: upon looking at the smelting abilities, it shows two possible results, that of the dyed glass, or vanilla glass. This includes the Create method of smelting (fan behind lava). It does have the proper fan behind soul campfire to turn it into soul sand ("vanilla" create thing) result. 

Fix? Smelt via regular furnace (and modded furnaces) = glass, Smelt via Create blast smelting = colored glass?  ... either that, or just have all of them do the colored glass? As this is a "rare" find resource?

**Comment by KinamKrindar** [comment]
Another conflicting Smelting result: Iron Bar smelting shows two results, that of Steel Ingot (Ad Astra), and Industrial Grade Metal (FTB Industrial Contraptions)

Current result of smelting / bulk smelting = the Industrial Grade Metal

Also, result from smelting the previously mentioned coloured sands yields plain glass.

**Comment by m1jordanallen** [comment]
fixed the metal/steel issue. I will consider the other fix if it becomes an annoyance
