### ISSUE TITLE
Ender Pouch from Ender Storage

### ISSUE THREAD

**Issue by 4tw0ne** [m1jordanallen/1.19OceanSurvival#27]
Multimc 0.0.4 

When viewing the ender pouch recipe from inventory, or JEI, it crashes.

[Hard Crash when looking up the uses for Ender Pouch from Ender Storage.txt](https://github.com/m1jordanallen/1.19OceanSurvival/files/12246481/Hard.Crash.when.looking.up.the.uses.for.Ender.Pouch.from.Ender.Storage.txt)

**Comment by ka13btv** [comment]
Seems this is a known issue with Create

https://github.com/Creators-of-Create/Create/issues/4122

**Comment by 4tw0ne** [comment]
Further research...

This occurs on all three items from EnderStorage.
Obtaining the Uses on any of these items, will crash a Modpack with "JEI, Create, EnderStorage" installed.

Crash bug fixed by updating mods. Likely only create is needed, but I also updated JEI.
Version with fix: create-1.19.2-0.5.1.i
