### ISSUE TITLE
Right clicking on crafting table with gold nuggets in hand

### ISSUE THREAD

**Issue by OmIAm** [m1jordanallen/1.19OceanSurvival#36]
Gives this error:

![image](https://github.com/m1jordanallen/1.19OceanSurvival/assets/141457221/70a0ad37-a5e4-4b9a-a935-ef0548f1cddc)

This is in the 0.0.6 experimental build.

**Comment by MrSelenix** [comment]
Save you looking at the output
![1](https://github.com/m1jordanallen/1.19OceanSurvival/assets/37115839/e941fa32-6748-40ab-90fb-039840bc85c8)

**Comment by MrSelenix** [comment]
Does not happen in 0.0.5

**Comment by m1jordanallen** [comment]
this is intended as a pack utility, I have a note to remove it before public, but this is actually intended. 

Part of playing alpha bois :)
