### ISSUE TITLE
Flight should be locked behind elytra -bams

### ISSUE THREAD

**Issue by OmIAm** [m1jordanallen/1.19OceanSurvival#42]
Blade on gyro is made with iron.  Make the center block an elytra instead?  Not sure what the plane recipe is but something similar would work.

**Comment by OmIAm** [comment]
Here's the propeller with an elytra in the recipe.

immersive_aircraft-0.5.1+1.19.2-forge\data\immersive_aircraft\recipes\propeller.json

[propeller.zip](https://github.com/m1jordanallen/1.19OceanSurvival/files/12509178/propeller.zip)

**Comment by m1jordanallen** [comment]
done in 0.0.8
