### ISSUE TITLE
Add some kind of item pipe mod maybe.

### ISSUE THREAD

**Issue by MrSelenix** [m1jordanallen/1.19OceanSurvival#44]
Might be worth adding something like Pipez or similar for basic item transport besides using create belts and funnels. Unless theres something ive not found that moved items about

**Comment by m1jordanallen** [comment]
Jon essentially made this decision. He needs to put in a request for something like this.

**Comment by m1jordanallen** [comment]
added a few mods that dont add pipes, but do add transfer
