### ISSUE TITLE
Remove or otherwise reduce the icy thorns enchants

### ISSUE THREAD

**Issue by MrSelenix** [m1jordanallen/1.19OceanSurvival#48]

**Comment by m1jordanallen** [comment]
Done in 0.0.7

We shal see how this goes:

Enchant Changes:
- Removed icy thorns
- Removed siphoning
- All protections reduced to max 4 and made less common
- Feather falling reduced to 6
- Thorns reduced to 3
- Sharpness reduced to 5
- Smite reduced to 5
- Power reduced to 5
- Punch reduced to 2
- Impaling reduced to 5
- Quick charge reduces to 3
- Piercing reduced to 4
