### ISSUE TITLE
Crash getting info from boots

### ISSUE THREAD

**Issue by 4tw0ne** [m1jordanallen/1.19OceanSurvival#54]
MultiMC, 0.0.6 10GB ram allocated

Crashes when I hover over an enchanted pair of boots in a chest. 

[crash-2023-08-11_19.20.08-client.txt](https://github.com/m1jordanallen/1.19OceanSurvival/files/12331324/crash-2023-08-11_19.20.08-client.txt)

**Comment by m1jordanallen** [comment]
Is this persistent or something easily reproduced?

**Comment by 4tw0ne** [comment]
While the boots were in a chest, it happened any time I hovered over them with my mouse. 

Since then I have sucked all of the items into a crafting grid. Of which does not produce the crash. 
Even if placed back into a chest, it now no longer crashes.

**Comment by m1jordanallen** [comment]
weird

Thank you for responding :)
