### ISSUE TITLE
Deeper Dark crash upon boot

### ISSUE THREAD

**Issue by 4tw0ne** [m1jordanallen/1.19OceanSurvival#60]
Multimc 0.0.6 - 10GB of RAM installed. 

When loading the game it crashed and gave this file:

[crash-2023-08-19_13.28.48-fml.txt](https://github.com/m1jordanallen/1.19OceanSurvival/files/12386507/crash-2023-08-19_13.28.48-fml.txt)

Here is latest log as well:

[latest.log](https://github.com/m1jordanallen/1.19OceanSurvival/files/12386508/latest.log)

**Comment by m1jordanallen** [comment]
was this only once? or is this still happening?

**Comment by 4tw0ne** [comment]
This was only once. I cannot get it to happen again

**Comment by m1jordanallen** [comment]
Thanks for responding!
