### ISSUE TITLE
Infernal bosses

### ISSUE THREAD

**Issue by ka13btv** [m1jordanallen/1.19OceanSurvival#63]
All bosses (especially the Divine RPG bosses) should be infernal - as confirmed with Jon

**Comment by m1jordanallen** [comment]
elder guardian and dragon are now always infernal. I need a list of bosses to make infernal tho. There are SO MANY entities, lol.

**Comment by ka13btv** [comment]
[bosses.csv](https://github.com/m1jordanallen/1.19OceanSurvival/files/12407930/bosses.csv)
This is a preliminsary list of bosses. I will refine it, but it's a starting point.

**Comment by m1jordanallen** [comment]
Divine RPG bosses cant be added :(

I did add others, but still need to do more

**Comment by m1jordanallen** [comment]
The ones possible have been added, but more balancing is needed. Closing this specific issue for now
