### ISSUE TITLE
Limit number of hearts -bams

### ISSUE THREAD

**Issue by OmIAm** [m1jordanallen/1.19OceanSurvival#64]
He suggested 20.

**Comment by 4tw0ne** [comment]
Do you recall any context on this one? 

Full videos from this time are here
https://www.youtube.com/watch?v=YJuVMyqq7vY&list=PLoVtrrBiUtUTOqyDPrm6AFoqzSr384Vy6&index=33

**Comment by OmIAm** [comment]
I don't, exactly.  But given how I put it and when this was, It may have been him complaining about health being overpowered right after he started playing it.

**Comment by 4tw0ne** [comment]
I am closing this one as "will not implement".
Things have changes much since the initial report, and the tanky amount of hearts is crucial to current gameplay.
