### ISSUE TITLE
Make everything from building gadgets mod slightly more expensive to craft

### ISSUE THREAD

**Issue by MrSelenix** [m1jordanallen/1.19OceanSurvival#71]
suggested by jon

**Comment by OmIAm** [comment]
Added blaze powder to all and ender pearl to one.

Four recipes in the zip in this folder

buildinggadgets-3.16.2-build.22+mc1.19.2\data\buildinggadgets\recipes\

[building gadget recipes.zip](https://github.com/m1jordanallen/1.19OceanSurvival/files/12509075/building.gadget.recipes.zip)

**Comment by 4tw0ne** [comment]
planned for "next" build
