### ISSUE TITLE
Fix for kobblins spawning on dreadful dirt

### ISSUE THREAD

**Issue by OmIAm** [m1jordanallen/1.19OceanSurvival#75]
This just removes the kobblins, tested and it works.  He wanted the farseer removed at one time but I think he got over that one.

mob_grinding_utils-1.19.2-0.4.49\data\mob_grinding_utils\tags\entity_types\no_dirt_spawn.json

{
  "values": [
    {
      "id": "divinerpg:kobblin",
      "required": false
    }
  ]
}

**Comment by OmIAm** [comment]
[no_dirt_spawn.zip](https://github.com/m1jordanallen/1.19OceanSurvival/files/12506884/no_dirt_spawn.zip)

**Comment by m1jordanallen** [comment]
koblins no longer in pack :(
