### ISSUE TITLE
Golems

### ISSUE THREAD

**Issue by OmIAm** [m1jordanallen/1.19OceanSurvival#77]
Golems are too easy to beat.  I believe I added them all to the anti-knockback list, but they need to be amped up somehow.  More health, more armor...  I'm not sure if infernal is the way to go, but it's definitely an option.

Here's the list:

ars_nouveau:amethyst_golem
ars_nouveau:familiar_amethyst_golem
blue_skies:artificial_golem
cataclysm:ender_golem
divinerpg:apalachia_golem
divinerpg:golem_of_rejuvenation
divinerpg:skythern_golem
divinerpg:stone_golem
divinerpg:wildwood_golem
minecraft:iron_golem
minecraft:snow_golem
mobz:icegolem
mobz:lavagolem
mobz:metalgolem
mobz:stonegolem

**Comment by 4tw0ne** [comment]
Golems left...
blue_skies:artificial_golem
cataclysm:ender_golem
minecraft:iron_golem
minecraft:snow_golem < - left useless :) 
mobz:icegolem
mobz:lavagolem
mobz:metalgolem
mobz:stonegolem

Buffed and added to mctweak antiKnockback
0.0.11a
