### ISSUE TITLE
Loot pinata

### ISSUE THREAD

**Issue by OmIAm** [m1jordanallen/1.19OceanSurvival#86]
Tone this down to only 2-3x the normal loot instead of 20 or whatever it is now?

**Comment by OmIAm** [comment]
I've been unable to find this to suggest a fix.

**Comment by m1jordanallen** [comment]
configging apotheosis is not fun :(

**Comment by 4tw0ne** [comment]
Apoth Affix 'Loot Piñata' (source [here](https://github.com/Shadows-of-Fire/Apotheosis/blob/0ec325b924b8867a723bec3b8c2c0a32e6140c8f/src/main/resources/data/apotheosis/affixes/sword/special/festive.json)) and the apoth enchantment 'Scavenger' [max level: 3] (source [here](https://github.com/Shadows-of-Fire/Apotheosis/blob/0ec325b924b8867a723bec3b8c2c0a32e6140c8f/src/main/java/shadows/apotheosis/ench/enchantments/masterwork/ScavengerEnchant.java)) are able to be on the same weapon, causing a potentially Large amount of items to be generated on a mob kill.

Loot piñata configs allows changing the rates the effect procs and which tiers they exist on. But the amount of loot itself is hard coded.
Scavenger, being an enchantment, can be limited to 'level 1' if needed.

Ultimately, leaving this 'as is' may be fine. Once a player discovers this combination, and abuses it, will quickly get sick of the amount of garbage they are sorting through. 

A fix suggestion if needed: somehow make it so these two are incompatible with each other. For example, 'any weapon that already has Loot Piñata cannot have Scavenger applied to it', and the reverse, if 'a weapon has Scavenger it cannot obtain Piñata'.

**Comment by 4tw0ne** [comment]
Scavenger  has been limited to Max Level 1, and removed from the enchant table but is still obtainable. 
0.0.11a
