### ISSUE TITLE
Create Crushing Wheel crushed ores issue

### ISSUE THREAD

**Issue by KinamKrindar** [m1jordanallen/1.19OceanSurvival#87]
The following ores can be crushed with Create's Crushing wheels, yielding a crushed raw <ore>, however they are currently not useable (no further processing capabilities)
Tin, Aluminum, Lead, Uranium

Currently, the crushed raw ores from create that do have further processing capabilities; can be cooked into a single bar via smelter/blast smelter/blast smelting via create's fans through lava, But the real "joy" is to "wash" the crushed ores with the create water fans, yielding at least 9 nuggets of the <type>, with a chance of other materials from the washing process

Currently looking through JEI: washing things has the following additional results on top of the 9 nuggets:
Zinc = 25% gunpowder
Gold = 50% nether quartz
Copper = 50% clay ball
Iron =75% redstone dust

I've seen other packs where the results are always the 9 nuggets, but occasionally granting extra nuggets as a result, which, I'd prefer honestly for the "less" chance of clogging inventory with random extra things not planned. I know there's recipes out there that have multiple "extra roll on loot" so to say for grinding things / washing things with create. and each additional slot has it's own % chance of having that result added to the resulting process finish, so you could actually have it where washing gives the guaranteed 9 nugs, a 25% for 2 more nugs, another 25% chance for 2 more nugs, and a final 10% chance for another random 1 nug ... 

I dunno, all up to you and the recipe design, however, I'm requesting at least having it where the crushed Tin, Aluminum, Lead, and Uranium ores that create has already as results for using those ores in the crushing wheels, able to be smelted into their respective bars, or washed into at least the 9 nuggets of those ores (all 4 look to have both bars and nugget forms of the items). As for current "extras" if you were to work with what you've got going on default for the other ores, that's a difficult thing to think about adding in, but looking at most of their uses, mostly I'd only see a result of "more nuggets" from washing as a good result, but not even needing much more.

**Comment by 4tw0ne** [comment]
I have the fix suggested above, setup. it just needs worked into a build

**Comment by 4tw0ne** [comment]
This was introduced in build 0.0.10b
