### ISSUE TITLE
Fishing Valley Crash

### ISSUE THREAD

**Issue by MrSelenix** [m1jordanallen/1.19OceanSurvival#90]
MP 0.0.8
2 fish particle effect things spawned, both hit the (legendary) fishing rod at the same time and crashed the game.
![Screenshot 2023-10-14 113920](https://github.com/m1jordanallen/1.19OceanSurvival/assets/37115839/1a72c036-f15e-422f-868b-b54e5564e234)
[crash-2023-10-14_11.39.15-server.txt](https://github.com/m1jordanallen/1.19OceanSurvival/files/12904584/crash-2023-10-14_11.39.15-server.txt)

**Comment by CedKilleur** [comment]
FIXED in version 0.9.6 and above
