### ISSUE TITLE
Reduce spawn frequency of bunny slippers -bams

### ISSUE THREAD

**Issue by OmIAm** [m1jordanallen/1.19OceanSurvival#91]
He's going to end up getting frustrating not finding them though....  Maybe don't turn it down far?

**Comment by 4tw0ne** [comment]
This likely does not need adjusting. Seems like he has a balance on the time it takes to discover them.

Note: These are not only in the loot injects (which are weight based), they are also coded to specific loot tables too (of which are not affected by the former method.)
