### ISSUE TITLE
Cyclopsian Staff -bams

### ISSUE THREAD

**Issue by OmIAm** [m1jordanallen/1.19OceanSurvival#92]
The divinerpg:cyclopsian_staff is OP with the talisman.

I looked and was unable to find a way to exclude stuff from the talisman effects.  If there's no way to remove the talisman effect from this, it needs to only spawn in high level loot or be removed entirely.

Alternative:

Requires Cyclops Eye to craft, which is 9 cyclops eye shards.  They aren't craftable.  Maybe just remove it from the loot tables but leave it craftable?

**Comment by m1jordanallen** [comment]
divine RPG removed
