### ISSUE TITLE
Config or remove iron furnaces

### ISSUE THREAD

**Issue by m1jordanallen** [m1jordanallen/1.19OceanSurvival#93]

**Comment by 4tw0ne** [comment]
The biggest comparison between IronFurnaces and IronGenerators is that IF does not waste fuel when power reserve is full. It will pause the consumption and hold till there is more demand. 

IG just keeps burning the fuel items regardless, wasting fuel even when there is no demand.

**Comment by m1jordanallen** [comment]
done in 0.0.9
