### ISSUE TITLE
Add custom recipe for prismarine bee

### ISSUE THREAD

**Issue by MrSelenix** [m1jordanallen/1.19OceanSurvival#94]

**Comment by MrSelenix** [comment]
Option 1; add to custom fishing loot. maybe tier 3+ rods for progression limiting?
Option 2; custom breeding recipe if possible to add

**Comment by MrSelenix** [comment]
marking as probably working (tbd)

**Comment by 4tw0ne** [comment]
Prismarine bee confirmed in Fishing valley loot
