### ISSUE TITLE
Flux "useless" recipes

### ISSUE THREAD

**Issue by 4tw0ne** [m1jordanallen/1.19OceanSurvival#95]
In the Flux Networks mod there are a couple recipes that are just cyclical, with no reason.

Flux plug
Flux point
Flux Controller
Flux Basic, Herculean, Gargantuan storages

All of these you can put the item into a "shapeless recipe" to just pull out the same item again. 

It may help to remove these recipes to prevent confusion over them.

**Comment by m1jordanallen** [comment]
This is intended as an easy settings reset. Doing this will reset the NBT of the item.

**Comment by OmIAm** [comment]
Is that global and for all items, or just that mod?
