### ISSUE TITLE
Cachalot Whale targeting player

### ISSUE THREAD

**Issue by OmIAm** [m1jordanallen/1.19OceanSurvival#99]
They are supposed to be neutral, the reason they aren't is improvedmobs settings.

In config/improvedmobs/common.toml there's a black/whitelist section. This:

"alexsmobs:cachalot_whale"

Should be replaced with:

"alexsmobs:cachalot_whale|NEUTRALAGGRO"

I tested with 64 spawned in ones and none were aggroed.

**Comment by m1jordanallen** [comment]
lower damage via Ced's magic

**Comment by OmIAm** [comment]
Works, and keeps other possible issues from showing up with it.  I have a feeling the squid are going to win a lot more often now though! :P

**Comment by m1jordanallen** [comment]
whale now does 1 damage
